#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo "\n\n"
echo "----------------------------------------"
echo "PRE-COMMIT HOOK RUNNING"
echo "----------------------------------------"

npx lint-staged --allow-empty
